development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: aa1jh98umjssqxu.czb4daseyrbp.ap-southeast-2.rds.amazonaws.com
  database: ebdb
  username: ebroot
  password: hmas754berries
  port: 3306
  

#Heroku will override this setting.
staging: 
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000