development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: /u/apps/jqclient/shared/db/production.sqlite3
  pool: 5
  timeout: 5000

#Heroku will override this setting.
staging: 
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000